### ISSUE TITLE
Add a rule to enforce fixme context

### ISSUE THREAD

**Issue by toejough** [openlyinc/openlynt#1]
godox is great, but we would like to make an exception to FIXME, XXX, etc when we have an issue link _and a few lines of context_ following it.

Should trigger a failure:
```go
// FIXME: https://path/to/issue
// FIXME: some super short message (https://path/to/issue)
```

Should be fine:
```go
// FIXME: https://path/to/issue
// what needs to get fixed
// also something about why we're not fixing it yet
```

Should be:
* comment-style agnostic
* FIXME/TODO/XXX agnostic
* short, same-line descriptor message agnostic

**Comment by chrsm** [comment]
Added a new type to the linter: `comment_group`.

```yaml
rule_short_name:
  type: comment_group
  name: Friendly Rule Name

  if:
    text: REGEXP

  require:
    # optional
    text: REGEXP

    # optional
    len: int
```

For example:

```
rule_todo:
  type: comment_group
  name: TODO Requirement
  if:
    text: TODO

  require:
    text: "https?://github.com/your/project/issues/\\d+"
    len: 2
```

This merge also brought in some structural changes I was working on, so we will need to update our definitions.
